name: "Deployment Action"
description: "Creates a GitHub Deployment status update"
author: "chrnorm"
inputs:
  state:
    description: "State for the deployment"
  token:
    description: "Github repository token"
  log_url:
    description: "Log url location"
  environment_url:
    description: "Sets the URL for accessing your environment"
  environment:
    description: "Will be used to get the deployment if no deployment_id is given"
  description:
    description: "Descriptive message about the deployment"
  auto_inactive:
    description: "Adds a new inactive status to all prior non-transient, non-production environment deployments with the same repository and environment name as the created status's deployment"
    default: "false"
  deployment_id:
    description: "The ID of the deployment"
runs:
  using: "node12"
  main: "dist/index.js"
